// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqkjNCT-QVh493slRd628mWDvYYMVEfR8',
    appId: '1:474288570572:web:01fc90db683c2dc35e4269',
    messagingSenderId: '474288570572',
    projectId: 'flutter-chat-app-e96bf',
    authDomain: 'flutter-chat-app-e96bf.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e96bf.appspot.com',
    measurementId: 'G-715PMFWY5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI869-PTyyVfzthMBkRbGO41rpwVZ1rZ0',
    appId: '1:474288570572:android:248966b7bc8cd35e5e4269',
    messagingSenderId: '474288570572',
    projectId: 'flutter-chat-app-e96bf',
    storageBucket: 'flutter-chat-app-e96bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANm22jzqesDhiTNdIe5CyOv3f8Kh0VW1I',
    appId: '1:474288570572:ios:0e02442d09ee04ae5e4269',
    messagingSenderId: '474288570572',
    projectId: 'flutter-chat-app-e96bf',
    storageBucket: 'flutter-chat-app-e96bf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANm22jzqesDhiTNdIe5CyOv3f8Kh0VW1I',
    appId: '1:474288570572:ios:5c02502729ea107d5e4269',
    messagingSenderId: '474288570572',
    projectId: 'flutter-chat-app-e96bf',
    storageBucket: 'flutter-chat-app-e96bf.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
